// angular/components/carousel/carousel.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-carousel',
  templateUrl: './carousel.component.html',
  styleUrls: ['./carousel.component.scss']
})
export class CarouselComponent {
  @Input() images: string[] = []; 
  @Input() width: number = 800; 
  @Input() height: number = 300; 
  @Input() autoSlide: boolean = true; 
  @Input() autoSlideInterval: number = 2000; 

  currentIndex: number = 0;

  nextSlide(): void {
    this.currentIndex = (this.currentIndex + 1) % this.images.length;
  }

  prevSlide(): void {
    this.currentIndex = (this.currentIndex - 1 + this.images.length) % this.images.length;
  }

  goToSlide(index: number): void {
    this.currentIndex = index;
  }
}

<div [style.width.px]="width" [style.height.px]="height" class="carousel-container">
  <!-- Slides -->
  <div class="carousel-wrapper" [style.transform]="'translateX(' + (-currentIndex * 100) + '%)'">
    <img [style.width.px]="width" [style.height.px]="height" *ngFor="let image of images" [src]="image"
      class="carousel-slide" alt="Slide">
  </div>

  <!-- Navigation Buttons -->
  <button class="carousel-btn prev" (click)="prevSlide()">&#10094;</button>
  <button class="carousel-btn next" (click)="nextSlide()">&#10095;</button>

  <!-- Dots Navigation -->
  <div class="carousel-dots">
    <button *ngFor="let image of images; let i = index" [class.active]="i === currentIndex" (click)="goToSlide(i)">
    </button>
  </div>
</div>

// react/components/carousel/carousel.jsx
import React, { useEffect, useState } from 'react';
import PropTypes from 'prop-types';
import './carousel.css';

const Carousel = ({ images, width = 800, height = 300, autoSlide = true, autoSlideInterval = 3000 }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  let slideInterval;

  // Next Slide
  const nextSlide = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  // Previous Slide
  const prevSlide = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 1 + images.length) % images.length);
  };

  // Go to a specific slide
  const goToSlide = (index) => {
    setCurrentIndex(index);
  };

  // Auto-slide functionality
  useEffect(() => {
    if (autoSlide) {
      slideInterval = setInterval(() => {
        nextSlide();
      }, autoSlideInterval);
    }

    return () => {
      if (slideInterval) clearInterval(slideInterval);
    };
  }, [autoSlide, autoSlideInterval, currentIndex]); // Re-run when currentIndex or autoSlide changes

  return (
    <div className="carousel-container" style={{ width: `${width}px`, height: `${height}px` }}>
      {/* Slides Wrapper */}
      <div
        className="carousel-wrapper"
        style={{
          transform: `translateX(-${currentIndex * 100}%)`,
          width: `${images.length * 100}%`,
        }}
      >
        {images.map((image, index) => (
          <img
            key={index}
            src={image}
            alt={`Slide ${index + 1}`}
            className="carousel-slide"
            style={{ width: `${width}px`, height: `${height}px` }}
          />
        ))}
      </div>

      {/* Navigation Buttons */}
      <button className="carousel-btn prev" onClick={prevSlide}>
        &#10094;
      </button>
      <button className="carousel-btn next" onClick={nextSlide}>
        &#10095;
      </button>

      {/* Navigation Dots */}
      <div className="carousel-dots">
        {images.map((_, index) => (
          <button
            key={index}
            className={`dot ${index === currentIndex ? 'active' : ''}`}
            onClick={() => goToSlide(index)}
          />
        ))}
      </div>
    </div>
  );
};

Carousel.propTypes = {
  images: PropTypes.arrayOf(PropTypes.string).isRequired,
  width: PropTypes.number,
  height: PropTypes.number,
  autoSlide: PropTypes.bool,
  autoSlideInterval: PropTypes.number,
};

export default Carousel;
